// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMW5KofRkaoBHwpU2Gkg3WbN9nfvIJNUI',
    appId: '1:187160490488:web:5651b357309163efbe260d',
    messagingSenderId: '187160490488',
    projectId: 'unifranzfind',
    authDomain: 'unifranzfind.firebaseapp.com',
    storageBucket: 'unifranzfind.appspot.com',
    measurementId: 'G-DDYGEGCX99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ22RBx7B96bnIxkNciIJwiOo54B9TTzM',
    appId: '1:187160490488:android:584b11e183a703c3be260d',
    messagingSenderId: '187160490488',
    projectId: 'unifranzfind',
    storageBucket: 'unifranzfind.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNmKMpKfYU0qCbs59GaM07mFbMRH31h-w',
    appId: '1:187160490488:ios:d9a95a1aa9ec5228be260d',
    messagingSenderId: '187160490488',
    projectId: 'unifranzfind',
    storageBucket: 'unifranzfind.appspot.com',
    iosBundleId: 'bo.edu.unifranzfind.unifranzfind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNmKMpKfYU0qCbs59GaM07mFbMRH31h-w',
    appId: '1:187160490488:ios:6f9d1eeef57ad849be260d',
    messagingSenderId: '187160490488',
    projectId: 'unifranzfind',
    storageBucket: 'unifranzfind.appspot.com',
    iosBundleId: 'bo.edu.unifranzfind.unifranzfind.RunnerTests',
  );
}
